---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    flux.weave.works/automated: "true"
  name: fcdemo-app
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: fcdemo-app
    spec:
      containers:
      - name: fcdemo-app
        image: mcas/franceconnect-agent-demo:latest
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: fcdemo-service
  labels:
    app: fcdemo-service
spec:
  type: LoadBalancer
  ports:
    # the port that this service should serve on
  - port: 80
    targetPort: 8000
    protocol: TCP
  selector:
    app: fcdemo-app
