---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: fcdemo-app
  annotations:
    flux.weave.works/automated: 'true'
spec:
  replicas: 4
  template:
    metadata:
      labels:
        app: fcdemo-app
    spec:
      containers:
      - name: fcdemo-app
        image: mcas/franceconnect-demo:latest
        ports:
        - containerPort: 3001
---
apiVersion: v1
kind: Service
metadata:
  name: fcdemo-service
  labels:
    app: fcdemo-service
spec:
  type: LoadBalancer
  ports:
    # the port that this service should serve on
  - port: 80
    targetPort: 3001
    protocol: TCP
  selector:
    app: fcdemo-app
