FROM arm32v7/node:20-slim as build

WORKDIR /app
COPY package*.json ./
RUN npm ci --omit=dev
COPY . ./

FROM arm32v7/node:20-slim

WORKDIR /app

COPY --from=build /app /app
EXPOSE 3001
CMD ["npm", "start"]
